const mockVideos = [
  {
    id: 1,
    title: "Alphabet Songs - Học chữ cái qua bài hát",
    description: "Video học chữ cái tiếng Anh qua các bài hát vui nhộn, giúp trẻ em ghi nhớ dễ dàng.",
    thumbnail: "https://readdy.ai/api/search-image?query=Colorful%20alphabet%20learning%20video%20thumbnail%20for%20children%2C%20cartoon%20style%2C%20educational%20content&width=400&height=225&seq=alphabet1&orientation=landscape",
    duration: "8:32",
    topic: "Alphabet",
    age: "4-7 tuổi",
    level: "Cơ bản",
    skill: "Nghe",
    price: "29,000đ",
    rating: 4.9,
    views: 2340,
    isPurchased: false,
    instructor: "Cô Emma",
    previewUrl: "#",
    tags: ["chữ cái", "bài hát", "cơ bản"]
  },
  {
    id: 2,
    title: "Colors & Shapes - Màu sắc và hình khối",
    description: "Học từ vựng về màu sắc và hình khối thông qua hoạt hình sinh động và dễ hiểu.",
    thumbnail: "https://readdy.ai/api/search-image?query=Colorful%20shapes%20and%20colors%20learning%20video%20for%20kids%2C%20bright%20educational%20animation&width=400&height=225&seq=colors1&orientation=landscape",
    duration: "6:15",
    topic: "Vocabulary",
    age: "4-7 tuổi", 
    level: "Cơ bản",
    skill: "Nghe",
    price: "25,000đ",
    rating: 4.8,
    views: 1890,
    isPurchased: true,
    instructor: "Cô Sarah",
    previewUrl: "#",
    tags: ["màu sắc", "hình khối", "từ vựng"]
  },
  {
    id: 3,
    title: "Family Members - Thành viên gia đình",
    description: "Giới thiệu các thành viên trong gia đình bằng tiếng Anh qua câu chuyện thú vị.",
    thumbnail: "https://readdy.ai/api/search-image?query=Happy%20family%20members%20cartoon%20illustration%20for%20English%20learning%20video&width=400&height=225&seq=family1&orientation=landscape",
    duration: "7:20",
    topic: "Vocabulary",
    age: "4-7 tuổi",
    level: "Cơ bản", 
    skill: "Nói",
    price: "32,000đ",
    rating: 4.7,
    views: 1560,
    isPurchased: false,
    instructor: "Thầy John",
    previewUrl: "#",
    tags: ["gia đình", "từ vựng", "giao tiếp"]
  },
  {
    id: 4,
    title: "Simple Greetings - Lời chào đơn giản",
    description: "Học cách chào hỏi cơ bản trong tiếng Anh qua các tình huống thực tế.",
    thumbnail: "https://readdy.ai/api/search-image?query=Children%20greeting%20each%20other%20cartoon%20style%20English%20learning%20illustration&width=400&height=225&seq=greeting1&orientation=landscape",
    duration: "5:45",
    topic: "Speaking",
    age: "4-7 tuổi",
    level: "Cơ bản",
    skill: "Nói", 
    price: "28,000đ",
    rating: 4.6,
    views: 2100,
    isPurchased: true,
    instructor: "Cô Emma",
    previewUrl: "#",
    tags: ["chào hỏi", "giao tiếp", "cơ bản"]
  },
  {
    id: 5,
    title: "Numbers 1-20 - Đếm số từ 1 đến 20",
    description: "Video học đếm số từ 1 đến 20 với hoạt hình vui nhộn và dễ nhớ.",
    thumbnail: "https://readdy.ai/api/search-image?query=Colorful%20numbers%201%20to%2020%20educational%20video%20thumbnail%20for%20children&width=400&height=225&seq=numbers1&orientation=landscape",
    duration: "9:10",
    topic: "Numbers",
    age: "4-7 tuổi",
    level: "Cơ bản",
    skill: "Nghe",
    price: "30,000đ", 
    rating: 4.8,
    views: 2890,
    isPurchased: false,
    instructor: "Cô Sarah",
    previewUrl: "#",
    tags: ["số đếm", "toán học", "cơ bản"]
  },
  {
    id: 6,
    title: "Daily Routines - Hoạt động hàng ngày",
    description: "Học từ vựng về các hoạt động hàng ngày qua video hoạt hình sinh động.",
    thumbnail: "https://readdy.ai/api/search-image?query=Daily%20routine%20activities%20for%20children%20cartoon%20educational%20illustration&width=400&height=225&seq=routine1&orientation=landscape",
    duration: "8:05",
    topic: "Vocabulary", 
    age: "8-10 tuổi",
    level: "Trung cấp",
    skill: "Nghe",
    price: "35,000đ",
    rating: 4.9,
    views: 1670,
    isPurchased: false,
    instructor: "Thầy Mike",
    previewUrl: "#",
    tags: ["hoạt động", "hàng ngày", "từ vựng"]
  },
  {
    id: 7,
    title: "Weather & Seasons - Thời tiết và mùa",
    description: "Tìm hiểu về thời tiết và các mùa trong năm bằng tiếng Anh.",
    thumbnail: "https://readdy.ai/api/search-image?query=Four%20seasons%20and%20weather%20educational%20cartoon%20for%20kids%20learning%20English&width=400&height=225&seq=weather1&orientation=landscape",
    duration: "7:55",
    topic: "Vocabulary",
    age: "8-10 tuổi",
    level: "Trung cấp", 
    skill: "Nói",
    price: "33,000đ",
    rating: 4.7,
    views: 1420,
    isPurchased: true,
    instructor: "Cô Emma",
    previewUrl: "#",
    tags: ["thời tiết", "mùa", "từ vựng"]
  },
  {
    id: 8,
    title: "Simple Present Tense - Thì hiện tại đơn",
    description: "Học ngữ pháp cơ bản về thì hiện tại đơn qua ví dụ thực tế.",
    thumbnail: "https://readdy.ai/api/search-image?query=Grammar%20learning%20illustration%20simple%20present%20tense%20for%20children%20education&width=400&height=225&seq=grammar1&orientation=landscape",
    duration: "10:30",
    topic: "Grammar",
    age: "8-10 tuổi",
    level: "Trung cấp",
    skill: "Viết",
    price: "38,000đ",
    rating: 4.6,
    views: 1890,
    isPurchased: false,
    instructor: "Thầy John", 
    previewUrl: "#",
    tags: ["ngữ pháp", "thì", "viết"]
  },
  {
    id: 9,
    title: "Animals & Their Sounds - Động vật và tiếng kêu",
    description: "Khám phá thế giới động vật và học cách phát âm tiếng kêu của chúng.",
    thumbnail: "https://readdy.ai/api/search-image?query=Cute%20cartoon%20animals%20making%20sounds%20educational%20video%20for%20children&width=400&height=225&seq=animals1&orientation=landscape",
    duration: "6:40",
    topic: "Vocabulary",
    age: "4-7 tuổi",
    level: "Cơ bản",
    skill: "Nghe",
    price: "31,000đ",
    rating: 4.8,
    views: 2540,
    isPurchased: true,
    instructor: "Cô Sarah",
    previewUrl: "#",
    tags: ["động vật", "âm thanh", "từ vựng"]
  },
  {
    id: 10,
    title: "Food & Drinks - Đồ ăn và thức uống", 
    description: "Học từ vựng về đồ ăn và thức uống qua video tương tác thú vị.",
    thumbnail: "https://readdy.ai/api/search-image?query=Colorful%20food%20and%20drinks%20cartoon%20illustration%20for%20English%20vocabulary%20learning&width=400&height=225&seq=food1&orientation=landscape",
    duration: "8:15",
    topic: "Vocabulary",
    age: "8-10 tuổi", 
    level: "Trung cấp",
    skill: "Nói",
    price: "36,000đ",
    rating: 4.9,
    views: 1780,
    isPurchased: false,
    instructor: "Cô Emma",
    previewUrl: "#",
    tags: ["đồ ăn", "thức uống", "từ vựng"]
  },
  {
    id: 11,
    title: "Basic Phonics - Ngữ âm cơ bản",
    description: "Học phát âm chữ cái và âm thanh cơ bản trong tiếng Anh.",
    thumbnail: "https://readdy.ai/api/search-image?query=Phonics%20learning%20cartoon%20with%20letters%20and%20sounds%20for%20children&width=400&height=225&seq=phonics1&orientation=landscape",
    duration: "11:20",
    topic: "Phonics",
    age: "4-7 tuổi",
    level: "Cơ bản",
    skill: "Đọc",
    price: "40,000đ",
    rating: 4.7,
    views: 1340,
    isPurchased: false,
    instructor: "Thầy Mike",
    previewUrl: "#",
    tags: ["ngữ âm", "phát âm", "đọc"]
  },
  {
    id: 12,
    title: "School Supplies - Đồ dùng học tập",
    description: "Tìm hiểu về các đồ dùng học tập bằng tiếng Anh qua hoạt hình.",
    thumbnail: "https://readdy.ai/api/search-image?query=School%20supplies%20cartoon%20illustration%20pencil%20book%20bag%20for%20English%20learning&width=400&height=225&seq=school1&orientation=landscape",
    duration: "7:25",
    topic: "Vocabulary",
    age: "8-10 tuổi",
    level: "Trung cấp",
    skill: "Viết", 
    price: "34,000đ",
    rating: 4.8,
    views: 1650,
    isPurchased: true,
    instructor: "Cô Sarah",
    previewUrl: "#",
    tags: ["học tập", "đồ dùng", "trường học"]
  }
];

export default mockVideos;